server:
  port: 8181
  servlet:
    context-path: /app
    session:
      timeout: 600s

spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/shop
    username: postgres
    password: admin
    driverClassName: org.postgresql.Driver
  jackson:
    serialization:
      INDENT_OUTPUT: true

  integrations:
    product-service:
      url: http://localhost:8180/app
      read-timeout: 10000
      write-timeout: 5000
      connect-timeout: 5000
    customer-service:
      url: http://localhost:8180/app
      read-timeout: 10000
      write-timeout: 5000
      connect-timeout: 5000